# Generated by Django 4.1.7 on 2023-03-24 09:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_list_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='descripton',
        ),
        migrations.AddField(
            model_name='list',
            name='time',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='list',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
